name: Hello Universe
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build_and_test:
    runs-on: ubuntu-20.04
  steps:
    - name: Clone code
      uses: actions/checkout@v2
    - name: Compine java file
      shell: bash
      run: javac Main.java
    - name: Rund the Java File he
      shell: bash
      run: java Main.java
